run:
  deadline: 10m
  skip-files: [ ]
  skip-dirs: [ ]

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
      - github.com/pkg/errors
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
      - unnamedResult
      - hugeParam
  gomoddirectives:
    replace-allow-list:
      - github.com/abbot/go-http-auth

linters:
  enable-all: true
  disable:
    - maligned # deprecated
    - interfacer # deprecated
    - scopelint # deprecated
    - golint # deprecated
    - exhaustivestruct # deprecated
    - execinquery # not relevant (SQL)
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - wsl
    - nlreturn
    - gomnd
    - goerr113
    - wrapcheck
    - exhaustive
    - exhaustruct
    - testpackage
    - tparallel
    - paralleltest
    - prealloc
    - forcetypeassert
    - bodyclose # Too many false positives: https://github.com/timakin/bodyclose/issues/30
    - ifshort # disable due to false-positive, the linter will be fixed https://github.com/esimonov/ifshort
    - varnamelen
    - nilnil
    - ireturn
    - errchkjson
    - contextcheck
    - nonamedreturns

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'G204: Subprocess launched with variable'
    - 'G304: Potential file inclusion via variable'
    - 'G102: Binds to all network interfaces'
  exclude-rules:
    - path: .*_test.go
      linters:
        - funlen
        - noctx
        - gochecknoinits
        - gochecknoglobals
        - maintidx
    - path: pkg/version/version.go
      linters:
        - gochecknoglobals
    # Digest auth uses md5 in tests.
    - path: pkg/acp/digestauth/digest_auth_request_test.go
      linters:
        - gosec
    # No need for cryptographically secured number generation here.
    - path: pkg/traefik/client.go
      text: 'G404: Use of weak random number generator \(math/rand instead of crypto/rand\)'
    - path: cmd/agent/run.go
      linters:
        - funlen
    # InsecureSkipVerify option set true on purpose.
    - path: pkg/traefik/client.go
      text: 'G402: TLS InsecureSkipVerify set true.'
